#!/bin/bash
clear
red='\e[1;31m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
yellow='\e[1;33m%s\e[0m\n'
blue='\e[1;34m%s\e[0m\n'
magenta='\e[1;35m%s\e[0m\n'
cyan='\e[1;36m%s\e[0m\n'
printf "$magenta"
 printf "$magenta" " .-----------------------------.           "
 printf "$magenta" " |  Hi Hackers                 |           "
 printf "$magenta" " |  Tool   : craw              |           "
 printf "$magenta" " |  Author : @karthi_the_hacker|           "
 printf "$magenta" " |           Jai Hind          |           "
 printf "$magenta" " '-----------------------------'           "
 printf "$yellow" "                 ^      (\_/)    "
 printf "$yellow" "                 '----- (O.o)    "
 printf "$yellow" "                        (> <)    "
printf "$magenta" ""
path=$(pwd)
dom=$1
while read dm ;
	do
	    gau $dm | tee -a $path/craw.txt  
done < $dom
